name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Install Chromium
      run: sudo apt-get install -y chromium-browser

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Run tests
      run: npm run test

    - name: Generate Allure report
      run: npm run allure-generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token:  ${{ secrets.GH_TOKEN }}
        publish_dir: ./allure-report
